services:
  tarkov-sound:
    image: nginx:alpine
    container_name: tarkov-sound-game
    ports:
      - "32082:80"
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped


